name: 'Run tests'

on:
    - push
    - pull_request

jobs:
    test:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os:
                    - windows-latest
                    - ubuntu-latest
                    - macos-latest

        name: Test on ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '14'
            - name: Setup python
              uses: actions/setup-python@v2
              with:
                python-version: 3.x
            - run: python3 -m pip install virtualenv
            - run: |
                  /usr/bin/Xvfb :99 -screen 0 1024x768x24 &
                  echo "Started xvfb"
              shell: bash
              if: matrix.os == 'ubuntu-latest'
            - run: npm ci
            - name: Cache node modules
              uses: actions/cache@v2
              with:
                  # npm cache files are stored in `~/.npm` on Linux/macOS
                  path: ~/.npm
                  key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: ${{ runner.os }}-
            - name: Run tests
              run: npm test
              env:
                  DISPLAY: ':99.0'
